# Site settings
title: Horizon Turf Nursery
email: team@variantstudios.com
description:
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://www.horizonturfnursery.com/" # the base hostname & protocol for your site
timezone: America/Denver

# Gems for plugins
gems:
  - jekyll-paginate # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6


# Permalinks
permalink: /blog/:year-:month-:day/:title/

#Collections
collections:
  sodtypes:
    output: true
    permalink: /sod-type/:title/

# Blog Settings
paginate: 3
paginate_path: "/blog/page:num/"

# Reading Time Feature
reading_time:     true
words_per_minute: 200

# Disqus Comments
disqus_short_name:
disqus_show_comment_count:

# typekit
typekit: "rge0cdc"

# Social Media
facebook:

# Google Analytics
google_analytics_tracking_id: "UA-41553392-1"

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
